"""Content for the SEO landing pages. Each page targets one search intent and has its own copy."""

SITE = "https://abdullahautomations.com"
BRAND = "Abdullah Automations"

SERVICES = [
    {
        "slug": "ai-automation-services",
        "nav": "AI automation",
        "keyword": "AI automation services",
        "title": "AI Automation Services for Small Businesses",
        "desc": "AI automation services that capture every lead, follow up automatically and keep your CRM up to date. Fixed-price projects from $1,200. Book a free call.",
        "h1": "AI automation services that do the repetitive work for you",
        "lede": "I build AI automations that take the busywork out of running a service business: saving leads, sending follow-ups, reminding customers, asking for reviews and reporting the numbers. They run in the background, every day, without anyone remembering to do them.",
        "price": "1200",
        "price_note": "Projects from $1,200, fixed price agreed before work starts.",
        "sections": [
            ("What AI automation means for a small business",
             ["AI automation connects the tools you already use, such as your website forms, inbox, calendar, CRM and messaging apps, and lets software handle the steps a person would otherwise do by hand. The AI part reads and writes like a person: it can understand a customer's message, pull out the details that matter and write a reply that sounds like your business.",
              "For most owners the result is simple. Leads stop slipping through the cracks, customers hear back in minutes instead of days, and your team spends its time on work that needs a human."]),
        ],
        "features": [
            ("Lead capture and CRM updates", "Every enquiry from your website, phone, WhatsApp or Instagram is saved to your CRM with the customer's details, what they asked for and where they came from."),
            ("Follow-up until they book", "Polite, personal follow-up messages go out by email or text until the lead books or says no, so warm leads never go cold."),
            ("Appointment reminders", "Customers get reminders before their booking, with a one-tap way to confirm or reschedule, which cuts no-shows."),
            ("Review requests", "After every job, happy customers are asked for a Google review at the right moment, which helps your local ranking."),
            ("Email and document handling", "Incoming emails are sorted, summarised and routed to the right person. Invoices, quotes and forms can be read and filed automatically."),
            ("Weekly reports", "A short summary of new leads, bookings and revenue lands in your inbox every Monday, without anyone building a spreadsheet."),
        ],
        "steps": [
            ("Map the work", "We list the tasks your team repeats every week and pick the ones that cost the most time or lose the most leads."),
            ("Design the flow", "You get a written plan showing each automation, the tools it connects and what happens in each case, with a fixed price."),
            ("Build and test", "I build the automations in tools like n8n, Make or Zapier, connect your accounts and test every path with real examples."),
            ("Launch and monitor", "We switch it on, I watch the first weeks closely, and you get a simple way to see what ran and what needs a person."),
        ],
        "tools": ["n8n", "Make", "Zapier", "HubSpot", "GoHighLevel", "Google Workspace", "Microsoft 365", "Calendly", "Stripe", "Shopify", "WhatsApp Business", "Slack"],
        "faqs": [
            ("What can be automated in my business?", "Anything that follows the same steps each time: saving leads, replying to common questions, sending reminders and follow-ups, moving data between apps, creating invoices and sending reports. On the strategy call we go through your week and find the tasks worth automating first."),
            ("Do I need to change the software I use?", "Usually not. I connect the tools you already have. If something can't be connected, I'll suggest the simplest alternative and explain why."),
            ("How long does an automation project take?", "Small projects take one to two weeks. A full set of automations for a business usually takes two to four weeks, including testing."),
            ("What happens if an automation breaks?", "Each automation has error alerts. On a care plan I monitor them and fix problems, usually before you notice."),
        ],
    },
    {
        "slug": "ai-agents",
        "nav": "AI agents",
        "keyword": "AI agents for business",
        "title": "AI Agents for Business: Chat, WhatsApp & Voice",
        "desc": "Custom AI agents that answer customers 24/7 on your website, WhatsApp, Instagram and phone, qualify leads and book appointments. Setup from $2,500.",
        "h1": "AI agents that answer, qualify and book for your business",
        "lede": "An AI agent is a trained assistant that talks to your customers for you. It knows your services, prices, hours and policies, answers questions in seconds, and books appointments straight into your calendar, day and night, on every channel your customers use.",
        "price": "2500",
        "price_note": "Setup from $2,500 plus a monthly care plan from $300.",
        "sections": [
            ("How an AI agent is different from an old chatbot",
             ["Old chatbots followed fixed menus and broke as soon as a customer asked something unexpected. A modern AI agent understands normal language, keeps track of the conversation and can take actions: checking your calendar, booking a slot, updating your CRM or sending a message to your team.",
              "It also knows when to stop. When a question falls outside what it has been taught, the agent hands the conversation to you instead of guessing."]),
        ],
        "features": [
            ("Website chat agent", "Answers visitors on your website and books them in while they are still interested, instead of leaving them to fill in a form and wait."),
            ("WhatsApp and Instagram agent", "Replies to DMs and WhatsApp messages in seconds, including evenings and weekends when most enquiries arrive."),
            ("AI voice receptionist", "Answers phone calls in a natural voice, takes bookings and messages, and texts back callers you missed."),
            ("Lead qualification", "Asks the questions you would ask, such as budget, timing and location, and sends hot leads straight to you."),
            ("Bookings and payments", "Books into Google Calendar, Calendly or your booking system and can take deposits through Stripe."),
            ("Many languages", "Replies in the language the customer writes in, including English, Arabic and Urdu."),
        ],
        "steps": [
            ("Teach it your business", "We gather your services, prices, hours, policies and the questions customers ask most."),
            ("Set the rules", "We decide what the agent can do on its own, what it must hand to a person, and how it should sound."),
            ("Connect your channels", "I connect the agent to your website, WhatsApp, Instagram, phone line, calendar and CRM."),
            ("Test, launch, improve", "You test it with real questions before launch, then I review conversations every month and keep improving it."),
        ],
        "tools": ["OpenAI", "Anthropic Claude", "WhatsApp Business API", "Instagram", "Twilio", "Vapi", "Google Calendar", "Calendly", "HubSpot", "GoHighLevel", "Stripe"],
        "faqs": [
            ("Will customers know they are talking to an AI?", "We recommend the agent introduces itself as an assistant. Customers mostly care about getting a fast, correct answer, and the agent hands over to a person whenever they ask."),
            ("Can the AI agent give wrong answers?", "It only answers from the information we give it, and it is set up to hand over when it is unsure. You test it before launch and can read every conversation."),
            ("Which channels can the agent work on?", "Your website chat, WhatsApp, Instagram and Facebook messages, SMS and phone calls. Most businesses start with one or two channels and add more later."),
            ("How much does an AI agent cost to run?", "Setup starts at $2,500. The monthly care plan starts at $300 and covers hosting, normal AI usage, monitoring and monthly improvements."),
        ],
    },
    {
        "slug": "website-design-services",
        "nav": "Website design",
        "keyword": "website design services",
        "title": "Website Design Services: Custom Premium Sites",
        "desc": "Custom website design services for businesses that want to look premium and win more enquiries. Video, motion, booking, SEO and AI built in. From $1,500.",
        "h1": "Website design services for businesses that want to look premium",
        "lede": "I design and build custom websites that make your business look like the obvious choice and turn visitors into enquiries. Every site is designed from scratch for your brand, loads fast, works on every phone, and can come with an AI agent built in.",
        "price": "1500",
        "price_note": "Websites from $1,500, fixed price agreed before work starts.",
        "sections": [
            ("Why a premium website pays for itself",
             ["Most customers look you up before they call. If your site looks dated, loads slowly or makes them hunt for a phone number, many will leave for a competitor without you ever knowing. A clear, fast, beautiful site does the opposite: it builds trust in seconds and makes the next step obvious.",
              "I build sites around one goal, more enquiries, and design every page to support it: clear headlines, proof of quality, simple booking and fast loading on mobile."]),
        ],
        "features": [
            ("Custom design, no templates", "Your site is designed for your brand and your customers, with its own colours, type and layout."),
            ("Video and motion", "Background video, scroll animation and small interactions that make the site feel premium without slowing it down."),
            ("Booking and payments", "Online booking, enquiry forms and deposits, connected to your calendar and CRM."),
            ("SEO built in", "Clean code, fast loading, page titles, structured data and a sitemap so Google can find and understand every page."),
            ("Mobile first", "Designed and tested for phones first, since most of your visitors arrive on one."),
            ("Easy to update", "Change prices, hours, text and photos yourself without calling a developer."),
        ],
        "steps": [
            ("Discovery", "We talk about your business, your customers and the sites you like, and agree on the pages and goals."),
            ("Design", "You see the homepage design first and choose a direction before anything is built."),
            ("Build", "I build the full site, connect booking and forms, and set up SEO and analytics."),
            ("Launch", "We test on every device, go live on your domain, and you get a walkthrough on making changes."),
        ],
        "tools": ["Custom HTML and CSS", "Astro", "Next.js", "Webflow", "WordPress", "Shopify", "Google Analytics", "Google Search Console", "Cloudflare", "Vercel"],
        "faqs": [
            ("How long does a website take to build?", "A typical business website takes two to three weeks from the first call to launch, depending on how many pages you need and how quickly content is ready."),
            ("Do you write the content?", "Yes. I can write the copy for every page based on a short interview with you, or edit text you already have."),
            ("Will my website rank on Google?", "Every site is built with technical SEO in place: fast loading, proper titles, structured data and a sitemap. Ranking also depends on content, reviews and links over time, and I can help with all of those."),
            ("Can I add an AI agent to my website later?", "Yes. Sites are built so an AI chat agent can be added at any time, and many clients start with the website and add the agent a month later."),
        ],
    },
]

INDUSTRIES = [
    {
        "slug": "dental-clinics", "name": "dental clinics", "short": "Dental clinics", "demo": "/demos/dental.html",
        "title": "AI Automation for Dental Clinics: AI Receptionist & Booking",
        "desc": "AI receptionist and automation for dental clinics: answer calls 24/7, book and remind patients, cut no-shows and answer insurance questions. Book a demo.",
        "h1": "AI automation for dental clinics",
        "lede": "Your front desk is busy with patients in the chair, so calls go to voicemail and new patients book somewhere else. An AI receptionist answers every call and message, books appointments into your schedule and reminds patients so fewer chairs sit empty.",
        "pains": [
            ("Missed calls during clinic hours", "When reception is checking someone in, the phone rings out. Many new patients call the next clinic on the list instead of leaving a message."),
            ("No-shows and late cancellations", "An empty chair is lost revenue you can't get back. Manual reminder calls take hours each week."),
            ("The same questions all day", "Do you take my insurance? How much is a cleaning? Are you open Saturday? Your team answers them again and again."),
            ("After-hours emergencies", "Patients in pain search at night and on weekends and book whoever answers first."),
        ],
        "solutions": [
            "Answers calls, website chat and WhatsApp 24/7 and books straight into your practice calendar",
            "Sends confirmations and reminders, and offers cancelled slots to patients on a waitlist",
            "Answers insurance, pricing and opening-hours questions from your own information",
            "Triages emergencies and offers the next urgent slot, or alerts the on-call dentist",
            "Sends new-patient forms before the visit so check-in is quick",
            "Asks happy patients for a Google review after their appointment",
        ],
        "convo": [("in", "Hi, my tooth is really hurting. Can I get in tomorrow?"), ("out", "Sorry you're in pain. I have an emergency slot tomorrow at 9:15 a.m. Shall I book it for you?"), ("in", "Yes please"), ("out", "Booked. You'll get a reminder tonight with directions and a short new-patient form.")],
        "tools": ["Dentrix", "Open Dental", "Dentally", "Google Calendar", "Twilio", "WhatsApp Business"],
        "faqs": [
            ("Can the AI receptionist book into my dental software?", "In most cases, yes. Many practice systems can be connected directly or through a booking tool. If yours can't, the agent books into a shared calendar that your team confirms."),
            ("Is patient information kept private?", "The agent only collects what is needed to book, uses accounts you own and can be set up to follow your data protection rules. Clinical questions are always passed to your team."),
            ("Will it handle emergency calls?", "Yes. It recognises urgent cases such as pain, swelling or a broken tooth, offers the next emergency slot and can alert the on-call dentist."),
        ],
    },
    {
        "slug": "real-estate", "name": "real estate agents", "short": "Real estate", "demo": "/demos/realestate.html",
        "title": "AI Automation for Real Estate Agents: Leads & Viewings",
        "desc": "AI automation for real estate agents: reply to portal leads in seconds, qualify buyers, book viewings and follow up automatically. Win more listings.",
        "h1": "AI automation for real estate agents",
        "lede": "In real estate the first agent to reply usually wins the client. An AI agent answers every portal, website and social enquiry in seconds, qualifies the buyer or seller, and books viewings straight into your calendar while you are out showing homes.",
        "pains": [
            ("Portal leads go cold fast", "A lead who waits hours for a reply has usually already spoken to another agent."),
            ("Time lost on unqualified leads", "Agents spend hours on people who aren't ready, can't get finance or are just browsing."),
            ("Phone tag for every viewing", "Arranging a single viewing can take five messages back and forth."),
            ("No follow-up after the first chat", "Buyers who aren't ready today are forgotten, then buy with someone else in three months."),
        ],
        "solutions": [
            "Replies to every enquiry from portals, your website, WhatsApp and Instagram within seconds",
            "Asks about budget, financing, timeline and must-haves, then scores the lead",
            "Books viewings into the right agent's calendar and sends directions and reminders",
            "Sends hot buyers and valuation requests straight to your phone",
            "Follows up with longer-term buyers with new listings that match what they asked for",
            "Answers listing questions from your property details any time of day",
        ],
        "convo": [("in", "Is the 3-bed on Marina Drive still available?"), ("out", "It is, listed at $845,000. Are you buying with a mortgage, and do you have pre-approval?"), ("in", "Pre-approved up to 900k"), ("out", "Great. I can book a private viewing Saturday at 11 or 2. Which suits you?")],
        "tools": ["Zillow", "Rightmove", "Property Finder", "Follow Up Boss", "HubSpot", "GoHighLevel", "Google Calendar"],
        "faqs": [
            ("Can the AI agent answer questions about specific listings?", "Yes. It reads your listing details, such as price, size, features and availability, and answers from them. Anything it doesn't know is passed to the listing agent."),
            ("Does it work with property portals?", "Leads from most portals arrive by email or through an integration, and the agent can reply to them instantly in the same thread or by text."),
            ("Will it replace my agents?", "No. It handles first replies, qualification and scheduling so your agents spend their time with serious buyers and sellers."),
        ],
    },
    {
        "slug": "restaurants", "name": "restaurants", "short": "Restaurants", "demo": "/demos/restaurant.html",
        "title": "AI Automation for Restaurants: Reservations, DMs & Reviews",
        "desc": "AI automation for restaurants: take reservations by chat, phone and Instagram, answer menu and allergy questions, capture private events and get more reviews.",
        "h1": "AI automation for restaurants",
        "lede": "When the dining room is full, nobody has time to answer the phone or reply to Instagram. An AI host takes reservations on every channel, answers menu and allergy questions, captures private event enquiries and asks happy guests for reviews.",
        "pains": [
            ("Phones ring during service", "Staff either ignore the phone or leave guests waiting at the table to answer it."),
            ("Booking requests stuck in DMs", "Reservations sent on Instagram and WhatsApp go unanswered until the next day."),
            ("Private events slip away", "Large, valuable event enquiries need quick, detailed replies that a busy manager can't always give."),
            ("Few reviews from happy guests", "Most happy guests never leave a review unless someone asks at the right moment."),
        ],
        "solutions": [
            "Takes reservations by website chat, Instagram, WhatsApp and phone, straight into your booking system",
            "Answers questions about the menu, dietary options, parking and opening hours",
            "Records allergies and special occasions on the booking for the kitchen and floor team",
            "Captures private event details such as date, group size and budget, and sends them to your events manager",
            "Sends reminders to cut no-shows and frees tables that won't be used",
            "Asks guests for a Google review after their visit",
        ],
        "convo": [("in", "Table for 6 tonight around 8?"), ("out", "I have 8:15 p.m. on the terrace or 8:30 p.m. inside. Any allergies I should tell the kitchen?"), ("in", "8:15 terrace, one person is gluten free"), ("out", "Done. Table for 6 at 8:15 p.m. on the terrace, gluten free noted. See you tonight!")],
        "tools": ["OpenTable", "SevenRooms", "Resy", "Toast", "Square", "Instagram", "WhatsApp Business"],
        "faqs": [
            ("Can the AI book into my reservation system?", "Yes for most popular systems. If yours can't be connected, the agent books into a shared calendar or sends confirmed details to your team."),
            ("How does it handle allergies?", "It records allergies on the booking and passes them to the kitchen. For detailed allergen questions it uses your allergen information or hands over to a person."),
            ("Can it answer the phone during service?", "Yes. An AI voice host can answer calls, take reservations and answer common questions so your staff can stay with guests."),
        ],
    },
    {
        "slug": "ecommerce", "name": "e-commerce stores", "short": "E-commerce", "demo": "/demos/store.html",
        "title": "AI Automation for E-commerce: Support Agent & Cart Recovery",
        "desc": "AI automation for e-commerce stores: answer support tickets 24/7, track orders, handle returns, recommend products and recover abandoned carts on Shopify.",
        "h1": "AI automation for e-commerce stores",
        "lede": "Online shoppers expect instant answers at any hour. An AI shopping assistant tracks orders, handles returns, recommends the right products and recovers abandoned carts, so your support inbox shrinks and more visitors turn into customers.",
        "pains": [
            ("\"Where is my order?\" fills the inbox", "Order status questions make up a large share of support tickets and take time from harder cases."),
            ("Shoppers leave with unanswered questions", "Questions about size, ingredients or delivery go unanswered, so the visitor leaves."),
            ("Abandoned carts with no follow-up", "Shoppers who added items but didn't buy rarely hear from you again."),
            ("Returns handled by hand", "Every return means back-and-forth emails, labels and refunds."),
        ],
        "solutions": [
            "Answers order tracking, shipping and returns questions instantly using your store data",
            "Recommends products based on what the shopper tells it, like a good shop assistant",
            "Starts returns and exchanges and sends return labels automatically",
            "Recovers abandoned carts with personal email and SMS follow-ups",
            "Hands complex or upset customers to your support team with the full conversation",
            "Collects product feedback and reviews after delivery",
        ],
        "convo": [("in", "Where's my order? #48213"), ("out", "Your order shipped yesterday and arrives Thursday. I've emailed you the tracking link."), ("in", "Can I add a cleanser to it?"), ("out", "That order has already left, but I've made a new cart with the cleanser and free shipping. Want the link?")],
        "tools": ["Shopify", "WooCommerce", "Klaviyo", "Gorgias", "Zendesk", "Stripe", "WhatsApp Business"],
        "faqs": [
            ("Does the AI agent work with Shopify?", "Yes. It can look up orders, products and customers in Shopify and answer from live data."),
            ("Can it process refunds?", "It can start returns and send labels. Refunds can be automatic for simple cases or approved by your team, depending on your rules."),
            ("Will it recommend the right products?", "It recommends from your catalogue based on what the customer tells it, and you control which products and rules it uses."),
        ],
    },
    {
        "slug": "law-firms", "name": "law firms", "short": "Law firms", "demo": None,
        "title": "AI Automation for Law Firms: Client Intake & Consultations",
        "desc": "AI automation for law firms: screen new enquiries by case type, book consultations, collect documents and keep clients updated, without adding staff.",
        "h1": "AI automation for law firms",
        "lede": "Potential clients often call several firms and hire the first one that responds properly. An AI intake assistant answers every enquiry, screens it by case type, books consultations with the right lawyer and collects documents before the first meeting.",
        "pains": [
            ("Intake takes lawyer time", "Fee earners spend hours on first calls with people who aren't a fit."),
            ("Enquiries go to the next firm", "If nobody answers, a potential client simply calls another firm."),
            ("Chasing documents by email", "Getting IDs, contracts and forms from clients slows every case down."),
            ("Clients calling for updates", "Status calls interrupt work and frustrate clients when nobody is free."),
        ],
        "solutions": [
            "Answers calls, website chat and messages around the clock",
            "Screens enquiries by practice area, location and urgency using your intake questions",
            "Books consultations into the right lawyer's calendar and takes fees if needed",
            "Collects documents and signed forms before the first meeting",
            "Sends clients automatic updates at each stage of their matter",
            "Keeps every enquiry logged in your case management or CRM system",
        ],
        "convo": [("in", "I need help with a tenancy dispute, my landlord is keeping my deposit."), ("out", "I'm sorry to hear that. I can book a 30-minute consultation with our property team. Is the property in the city?"), ("in", "Yes"), ("out", "Thanks. I have Thursday at 10:00 or 15:30 with Ms. Rahman. Which works for you?")],
        "tools": ["Clio", "MyCase", "PracticePanther", "Calendly", "DocuSign", "Microsoft 365"],
        "faqs": [
            ("Does the AI give legal advice?", "No. It collects information, answers general questions about your firm and books consultations. Legal questions are always passed to a lawyer."),
            ("Can it screen out enquiries we don't handle?", "Yes. It asks your intake questions and politely refers enquiries outside your practice areas or location."),
            ("Is client information kept confidential?", "The assistant runs on accounts you control and collects only what you need for intake. It can be set up to follow your confidentiality and data policies."),
        ],
    },
    {
        "slug": "fitness-studios", "name": "gyms and fitness studios", "short": "Fitness studios", "demo": None,
        "title": "AI Automation for Gyms & Fitness Studios: Trials & Retention",
        "desc": "AI automation for gyms and fitness studios: book free trials, follow up until they join, answer class questions and spot members about to cancel.",
        "h1": "AI automation for gyms and fitness studios",
        "lede": "Most studios lose members in two places: trials that never convert and members who quietly stop coming. An AI assistant books trials, follows up until people join, answers schedule questions and flags members who are likely to cancel.",
        "pains": [
            ("Trial sign-ups who never show up", "People book a trial, get busy, and never come in."),
            ("No follow-up after the trial", "Without a timely message, trial members drift away instead of joining."),
            ("Members cancel without a conversation", "By the time someone cancels, it's too late to win them back."),
            ("Class and pricing questions all day", "Front desk staff answer the same schedule and membership questions repeatedly."),
        ],
        "solutions": [
            "Books free trials and class spots from your website, Instagram and WhatsApp",
            "Sends reminders before the trial and personal follow-ups after it",
            "Answers class schedule, pricing and membership questions",
            "Flags members whose attendance drops and sends a friendly check-in",
            "Fills cancelled class spots from a waitlist",
            "Asks members for reviews and referrals at the right time",
        ],
        "convo": [("in", "Do you have beginner classes? I'd like to try one."), ("out", "We do! Beginner strength runs Monday and Wednesday at 7 p.m. Your first class is free. Shall I book Monday?"), ("in", "Yes, Monday"), ("out", "You're booked for Monday at 7 p.m. I'll send a reminder with what to bring.")],
        "tools": ["Mindbody", "Glofox", "ClassPass", "Zen Planner", "Stripe", "Instagram", "WhatsApp Business"],
        "faqs": [
            ("Can the AI book into Mindbody or Glofox?", "Many gym systems can be connected so bookings appear in your schedule automatically. If not, the agent books into a shared calendar your team confirms."),
            ("How does it help keep members?", "It watches for signs like fewer visits and sends a personal check-in or offer before the member decides to cancel."),
            ("Can it sell memberships?", "It can explain options, answer questions and send a payment link. You decide which offers it is allowed to make."),
        ],
    },
    {
        "slug": "home-services", "name": "home service businesses", "short": "Home services", "demo": None,
        "title": "AI Automation for Home Services: Missed-Call Text Back",
        "desc": "AI automation for plumbers, electricians, HVAC and cleaners: text back missed calls, book jobs, follow up on quotes and get more Google reviews.",
        "h1": "AI automation for home service businesses",
        "lede": "When you are on a job you can't answer the phone, and a missed call is usually a lost job. An AI assistant texts back every missed call in seconds, books the job, follows up on every quote and asks for a review when the work is done.",
        "pains": [
            ("Missed calls while on a job", "Customers with a leak or a power cut call the next company if you don't pick up."),
            ("Quotes that never get a reply", "Quotes are sent and forgotten, and many would have been won with one follow-up."),
            ("Scheduling by phone and text", "Arranging time windows takes several messages for every job."),
            ("Reviews only from unhappy customers", "Happy customers rarely leave a review unless someone asks."),
        ],
        "solutions": [
            "Texts back every missed call within seconds and finds out what the customer needs",
            "Books jobs into your calendar and confirms the arrival window",
            "Answers questions about services, areas covered and call-out fees",
            "Follows up on every open quote until the customer decides",
            "Sends on-the-way messages and job reminders",
            "Asks for a Google review when the job is marked complete",
        ],
        "convo": [("out", "Hi, this is Apex Plumbing. Sorry we missed your call! How can we help?"), ("in", "Water heater is leaking"), ("out", "We can have a technician there today between 2 and 4 p.m. The diagnostic visit is $89. Shall I book it?"), ("in", "Yes, 14 Cedar Lane")],
        "tools": ["Jobber", "Housecall Pro", "ServiceTitan", "Google Calendar", "Twilio", "QuickBooks"],
        "faqs": [
            ("How does missed-call text back work?", "When a call isn't answered, the customer gets a text within seconds. The AI assistant continues the conversation, finds out what they need and books the job."),
            ("Can it work with Jobber or Housecall Pro?", "Yes. Jobs and customers can be created in your field service software automatically."),
            ("Does it give prices?", "It can share call-out fees and standard prices you approve. Custom quotes are passed to you with all the details collected."),
        ],
    },
    {
        "slug": "salons-spas", "name": "salons and spas", "short": "Salons and spas", "demo": None,
        "title": "AI Automation for Salons & Spas: Instagram Booking",
        "desc": "AI automation for salons and spas: book appointments from Instagram and WhatsApp, fill last-minute gaps, remind clients to rebook and sell gift cards.",
        "h1": "AI automation for salons and spas",
        "lede": "Most salon bookings now start in a DM. An AI assistant replies to Instagram and WhatsApp messages instantly, books clients into your calendar, fills last-minute cancellations from a waitlist and reminds clients when it is time to come back.",
        "pains": [
            ("Booking requests stuck in DMs", "Stylists can't reply to messages while working, so clients book elsewhere."),
            ("Last-minute gaps in the schedule", "A late cancellation leaves an empty slot that nobody fills."),
            ("Clients forget to rebook", "Regulars drift away simply because nobody reminded them."),
            ("Questions about prices and services", "The same questions about colour, treatments and prices come in every day."),
        ],
        "solutions": [
            "Books appointments from Instagram, WhatsApp and your website into your salon software",
            "Answers questions about services, prices and stylists",
            "Fills cancellations by messaging clients on a waitlist",
            "Reminds clients when it's time to rebook based on their last visit",
            "Sells gift cards and packages with a payment link",
            "Asks for reviews after appointments",
        ],
        "convo": [("in", "Hi! Do you have anything for a balayage this Saturday?"), ("out", "Hi! Sara has 11:00 on Saturday. Balayage starts at $180 and takes about 3 hours. Shall I book it?"), ("in", "Yes please"), ("out", "Booked with Sara on Saturday at 11:00. I'll send a reminder on Friday.")],
        "tools": ["Fresha", "Vagaro", "Booksy", "Square Appointments", "Instagram", "WhatsApp Business", "Stripe"],
        "faqs": [
            ("Can the AI book into Fresha, Vagaro or Booksy?", "Many salon booking systems can be connected. Where they can't, the agent sends confirmed bookings to your team or uses a shared calendar."),
            ("Can it recommend the right stylist or treatment?", "Yes. It uses your service list and stylist skills to suggest the right option and price."),
            ("How does it fill cancellations?", "When a slot opens, it messages clients on your waitlist and books the first one to accept."),
        ],
    },
]

GUIDES = [
    {
        "slug": "what-is-ai-automation",
        "title": "What Is AI Automation? A Guide for Small Businesses",
        "desc": "What AI automation is, how it works, real examples for small businesses, what it costs and how to get started. A plain-English guide by Abdullah Automations.",
        "h1": "What is AI automation? A plain-English guide for small businesses",
        "lede": "AI automation means letting software handle repetitive work that used to need a person, including work that involves reading and writing. This guide explains how it works, where it helps small businesses most, what it costs and how to start without wasting money.",
        "body": [
            ("AI automation in one paragraph", ["Traditional automation follows fixed rules: when a form is submitted, add a row to a spreadsheet. AI automation adds a layer that can understand language. It can read a customer's message, work out what they want, pull out names, dates and budgets, and write a sensible reply. Put the two together and software can handle whole tasks, such as replying to a lead, booking them in and updating your CRM, not just single steps."]),
            ("Where small businesses get the most value", ["The best first projects are tasks that happen often, follow a similar pattern and cost you money when they are slow or forgotten. For most service businesses that means:"],
             ["Replying to new enquiries within seconds, at any time of day", "Booking appointments and sending reminders", "Following up with leads who haven't decided yet", "Saving every lead and conversation to a CRM", "Asking happy customers for reviews", "Sorting and summarising incoming email"]),
            ("AI automation vs. AI agents", ["The two terms overlap. AI automation usually describes workflows that run in the background, like follow-ups and reports. An AI agent is the part that talks to people: a chat, WhatsApp or voice assistant that holds a conversation and takes actions. Most businesses benefit from both: an agent at the front door and automations behind it. See the <a href=\"/guides/ai-agent-vs-chatbot/\">AI agent vs. chatbot guide</a> for more detail."]),
            ("What it costs", ["A focused automation project for a small business typically costs from around a thousand dollars, and a full system with an AI agent costs more. Ongoing costs cover hosting, AI usage and maintenance. The guide on <a href=\"/guides/how-much-does-ai-automation-cost/\">how much AI automation costs</a> breaks this down."]),
            ("How to start without wasting money", ["Start with one problem that clearly costs money, such as missed calls or slow lead replies. Measure it before you start, automate it, and compare after a month. Once the first automation pays for itself, add the next one."],
             ["Write down the tasks your team repeats every week", "Estimate the time each takes and what it costs when it goes wrong", "Pick the one with the clearest return", "Automate it, measure it, then move on to the next"]),
        ],
        "faqs": [
            ("Is AI automation only for big companies?", "No. Small businesses often benefit most, because a few hours saved each week or a few extra bookings each month make a big difference to a small team."),
            ("Do I need technical skills to use AI automation?", "No. Someone sets it up for you and connects it to your existing tools. You mostly see the results: replies sent, bookings made and leads saved."),
            ("Will AI automation replace my staff?", "It usually removes repetitive tasks rather than whole jobs, freeing your team for work that needs a person, like serving customers and doing the work you are paid for."),
        ],
    },
    {
        "slug": "ai-agent-vs-chatbot",
        "title": "AI Agent vs. Chatbot: What's the Difference?",
        "desc": "AI agents vs. chatbots explained: how they differ, what each can do, when a business needs an AI agent and what to look for before you buy one.",
        "h1": "AI agent vs. chatbot: what's the difference for your business?",
        "lede": "Chatbots and AI agents both talk to customers, but they are very different tools. This guide explains the difference in plain terms and helps you decide which one your business needs.",
        "body": [
            ("What a traditional chatbot does", ["A traditional chatbot follows a script. It shows buttons or expects certain words, then gives a fixed answer. It works for very simple questions, but it breaks as soon as a customer asks something in their own words or goes off script. Customers often find them frustrating."]),
            ("What an AI agent does", ["An AI agent understands normal language, remembers the conversation and can take actions in your systems. It can check your calendar and book a slot, look up an order, update your CRM, take a deposit or alert your team. It answers from your own information, and when it isn't sure, it hands over to a person."]),
            ("Side by side", ["Here is how the two compare on the things that matter to a business:"],
             ["Understanding: chatbots match keywords; AI agents understand full sentences and follow-up questions", "Actions: chatbots mostly answer; AI agents book, update, send and alert", "Channels: chatbots usually live on one website; AI agents can work on website, WhatsApp, Instagram and phone", "Setup: chatbots need every path scripted; AI agents are taught your information and rules", "Handover: both can hand over, but AI agents can summarise the conversation for your team"]),
            ("When you need an AI agent", ["If customers contact you through several channels, ask varied questions or need to book something, an AI agent is the better fit. If you only need a menu of links on one page, a simple chatbot may be enough. Most service businesses that lose leads to slow replies benefit from an AI agent. See <a href=\"/ai-agents/\">AI agents for business</a> for what a full setup includes."]),
            ("What to check before you buy", ["Whichever option you choose, check these points first:"],
             ["It answers only from information you approve", "It hands over to a person when unsure or when asked", "You can read every conversation", "It connects to your calendar and CRM", "You own the accounts and data"]),
        ],
        "faqs": [
            ("Is an AI agent the same as ChatGPT?", "AI agents often use the same kind of language model as ChatGPT, but they are set up for your business: trained on your information, connected to your tools and given clear rules."),
            ("Are AI agents expensive?", "Setup usually costs more than a basic chatbot because of the connections and testing involved, but the return comes from bookings and leads that would otherwise be lost."),
            ("Can an AI agent answer phone calls?", "Yes. Voice AI agents can answer calls in a natural voice, take bookings and messages, and text back callers you missed."),
        ],
    },
    {
        "slug": "how-much-does-ai-automation-cost",
        "title": "How Much Does AI Automation Cost? 2026 Pricing Guide",
        "desc": "How much AI automation and AI agents cost in 2026: setup prices, monthly costs, what drives the price and how to work out if it will pay for itself.",
        "h1": "How much does AI automation cost? A 2026 pricing guide",
        "lede": "AI automation pricing can look confusing because projects vary so much. This guide explains the typical costs for small businesses, what changes the price, and a simple way to check whether it will pay for itself.",
        "body": [
            ("Typical price ranges", ["These are the starting prices for the main types of project at Abdullah Automations. Other providers will differ, but the structure is similar across the market:"],
             ["Single automation project, such as lead capture to CRM with follow-ups: from $1,200", "AI agent for chat, WhatsApp or voice: setup from $2,500, plus a care plan from $300 a month", "Premium business website: from $1,500", "Full growth system with website, AI agent and automations: from $6,000, plus $600 a month"]),
            ("What changes the price", ["The biggest factors are the number of systems to connect, how many channels the AI agent works on, how much custom logic is needed and how much testing a workflow needs before it is safe to run on its own."],
             ["Number of tools and integrations", "Number of channels, such as web chat, WhatsApp, Instagram and phone", "Custom rules and edge cases", "Volume of messages and calls", "Whether design or copywriting is included"]),
            ("Ongoing costs", ["Most AI automation has some monthly cost: hosting and automation platforms, AI usage that grows with message volume, and maintenance. A care plan bundles these and includes monitoring and improvements, so the system keeps working as your business changes."]),
            ("Will it pay for itself?", ["Use this simple check. Estimate how many enquiries you miss or answer too late each month, how many of those would have become customers, and what a customer is worth to you. If an AI agent wins back even a small share of those, it often covers its monthly cost many times over. You can try the numbers in the calculator on the <a href=\"/#roi\">homepage</a>."]),
            ("How to get an accurate quote", ["Write down the channels customers use to contact you, the tools you already use and the tasks you want handled. A short strategy call turns that into a fixed-price proposal, so you know the full cost before any work starts."]),
        ],
        "faqs": [
            ("Is there a cheap way to start with AI automation?", "Yes. Start with one automation that solves your most expensive problem, such as missed-call text back or lead follow-up, then expand once it pays for itself."),
            ("Are there hidden costs?", "There shouldn't be. Ask for a fixed-price setup and a clear list of what the monthly fee covers, including what happens if your message volume grows."),
            ("How quickly will I see a return?", "Lead response and missed-call automations often show results within the first month, because every recovered lead is easy to count."),
        ],
    },
]
